<?php

namespace TechEventBundle\Repository;

/**
 * user_categorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class user_categorieRepository extends \Doctrine\ORM\EntityRepository
{
}
